const std = @import("std");
const types = @import("types.zig");

/// The fallback when a provider will not describe its own models.
///
/// `registry.zig` asks the provider first; this is what is left when the ask
/// fails, when the provider publishes nothing (OpenAI's /v1/models is ids
/// only), or when it publishes everything except the field wanted (only
/// Anthropic publishes effort levels).
///
/// Effort vocabularies are per vendor and per model, and a level the model
/// does not take is a rejected request, so these are transcribed from the
/// vendor docs rather than inferred:
///
///   xAI      low|medium|high|xhigh, default high, reasoning cannot be
///            disabled. `xhigh` is grok-4.6 and later; on grok-4.5 it is
///            silently treated as `high`. There is no `minimal`.
///            docs.x.ai/developers/model-capabilities/text/reasoning
///   OpenAI   per model, and there is no `minimal` on anything current:
///              gpt-5.6 (sol/terra/luna)  none|low|medium|high|xhigh|max
///              gpt-5.5                   none|low|medium|high|xhigh
///              gpt-5.x-codex             low|medium|high|xhigh
///            `max` is gpt-5.6 and later. `ultra` is not an effort value at
///            all -- it is a Codex mode that fans work out to subagents.
///            developers.openai.com/api/docs/guides/latest-model
///   Anthropic  published per model in the models endpoint; see registry.zig.
///
/// Context windows are per auth route as well as per model: see
/// `registry.authCap`. Checked 2026-08-22.
pub const Model = struct {
    id: []const u8,
    name: []const u8,
    provider: []const u8,
    protocol: types.Protocol,
    base_url: []const u8,
    reasoning: bool,
    context_window: u32,
    max_tokens: u32,
    /// Empty, or comma-separated: minimal,low,medium,high,xhigh,max
    efforts: []const u8,
    vision: bool,
};

pub const all = [_]Model{
    .{
        .id = "grok-4.20-0309-non-reasoning",
        .name = "Grok 4.20 (Non-Reasoning)",
        .provider = "xai-oauth",
        .protocol = .openai_responses,
        .base_url = "https://api.x.ai/v1",
        .reasoning = false,
        .context_window = 2000000,
        .max_tokens = 2000000,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "grok-4.20-0309-reasoning",
        .name = "Grok 4.20 (Reasoning)",
        .provider = "xai-oauth",
        .protocol = .openai_responses,
        .base_url = "https://api.x.ai/v1",
        .reasoning = true,
        .context_window = 2000000,
        .max_tokens = 2000000,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "grok-4.20-multi-agent-0309",
        .name = "Grok 4.20 (Multi-Agent)",
        .provider = "xai-oauth",
        .protocol = .openai_responses,
        .base_url = "https://api.x.ai/v1",
        .reasoning = true,
        .context_window = 2000000,
        .max_tokens = 2000000,
        .efforts = "low,medium,high,xhigh",
        .vision = false,
    },
    .{
        .id = "grok-4.3",
        .name = "Grok 4.3",
        .provider = "xai-oauth",
        .protocol = .openai_responses,
        .base_url = "https://api.x.ai/v1",
        .reasoning = true,
        .context_window = 1000000,
        .max_tokens = 1000000,
        .efforts = "low,medium,high",
        .vision = true,
    },
    .{
        .id = "grok-4.5",
        .name = "Grok 4.5",
        .provider = "xai-oauth",
        .protocol = .openai_responses,
        .base_url = "https://api.x.ai/v1",
        .reasoning = true,
        .context_window = 500000,
        .max_tokens = 500000,
        .efforts = "low,medium,high",
        .vision = true,
    },
    .{
        .id = "grok-4.6",
        .name = "Grok 4.6",
        .provider = "xai-oauth",
        .protocol = .openai_responses,
        .base_url = "https://api.x.ai/v1",
        .reasoning = true,
        .context_window = 500000,
        .max_tokens = 500000,
        .efforts = "low,medium,high,xhigh",
        .vision = true,
    },
    .{
        .id = "grok-build",
        .name = "Grok Build",
        .provider = "xai-oauth",
        .protocol = .openai_responses,
        .base_url = "https://api.x.ai/v1",
        .reasoning = true,
        .context_window = 512000,
        .max_tokens = 512000,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "grok-build-0.1",
        .name = "Grok Build 0.1",
        .provider = "xai-oauth",
        .protocol = .openai_responses,
        .base_url = "https://api.x.ai/v1",
        .reasoning = true,
        .context_window = 256000,
        .max_tokens = 256000,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "grok-composer-2.5-fast",
        .name = "Grok Composer 2.5 Fast",
        .provider = "xai-oauth",
        .protocol = .openai_responses,
        .base_url = "https://api.x.ai/v1",
        .reasoning = false,
        .context_window = 200000,
        .max_tokens = 200000,
        .efforts = "",
        .vision = false,
    },
    .{
        .id = "grok-2",
        .name = "Grok 2",
        .provider = "xai-api",
        .protocol = .openai_responses,
        .base_url = "https://api.x.ai/v1",
        .reasoning = false,
        .context_window = 131072,
        .max_tokens = 8192,
        .efforts = "",
        .vision = false,
    },
    .{
        .id = "grok-2-1212",
        .name = "Grok 2 (1212)",
        .provider = "xai-api",
        .protocol = .openai_responses,
        .base_url = "https://api.x.ai/v1",
        .reasoning = false,
        .context_window = 131072,
        .max_tokens = 8192,
        .efforts = "",
        .vision = false,
    },
    .{
        .id = "grok-2-latest",
        .name = "Grok 2 Latest",
        .provider = "xai-api",
        .protocol = .openai_responses,
        .base_url = "https://api.x.ai/v1",
        .reasoning = false,
        .context_window = 131072,
        .max_tokens = 8192,
        .efforts = "",
        .vision = false,
    },
    .{
        .id = "grok-2-vision",
        .name = "Grok 2 Vision",
        .provider = "xai-api",
        .protocol = .openai_responses,
        .base_url = "https://api.x.ai/v1",
        .reasoning = false,
        .context_window = 8192,
        .max_tokens = 4096,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "grok-2-vision-1212",
        .name = "Grok 2 Vision (1212)",
        .provider = "xai-api",
        .protocol = .openai_responses,
        .base_url = "https://api.x.ai/v1",
        .reasoning = false,
        .context_window = 8192,
        .max_tokens = 4096,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "grok-2-vision-latest",
        .name = "Grok 2 Vision Latest",
        .provider = "xai-api",
        .protocol = .openai_responses,
        .base_url = "https://api.x.ai/v1",
        .reasoning = false,
        .context_window = 8192,
        .max_tokens = 4096,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "grok-3",
        .name = "Grok 3",
        .provider = "xai-api",
        .protocol = .openai_responses,
        .base_url = "https://api.x.ai/v1",
        .reasoning = false,
        .context_window = 131072,
        .max_tokens = 8192,
        .efforts = "",
        .vision = false,
    },
    .{
        .id = "grok-3-fast",
        .name = "Grok 3 Fast",
        .provider = "xai-api",
        .protocol = .openai_responses,
        .base_url = "https://api.x.ai/v1",
        .reasoning = false,
        .context_window = 131072,
        .max_tokens = 8192,
        .efforts = "",
        .vision = false,
    },
    .{
        .id = "grok-3-fast-latest",
        .name = "Grok 3 Fast Latest",
        .provider = "xai-api",
        .protocol = .openai_responses,
        .base_url = "https://api.x.ai/v1",
        .reasoning = false,
        .context_window = 131072,
        .max_tokens = 8192,
        .efforts = "",
        .vision = false,
    },
    .{
        .id = "grok-3-latest",
        .name = "Grok 3 Latest",
        .provider = "xai-api",
        .protocol = .openai_responses,
        .base_url = "https://api.x.ai/v1",
        .reasoning = false,
        .context_window = 131072,
        .max_tokens = 8192,
        .efforts = "",
        .vision = false,
    },
    .{
        .id = "grok-3-mini",
        .name = "Grok 3 Mini",
        .provider = "xai-api",
        .protocol = .openai_responses,
        .base_url = "https://api.x.ai/v1",
        .reasoning = true,
        .context_window = 131072,
        .max_tokens = 8192,
        .efforts = "low,medium,high",
        .vision = false,
    },
    .{
        .id = "grok-3-mini-fast",
        .name = "Grok 3 Mini Fast",
        .provider = "xai-api",
        .protocol = .openai_responses,
        .base_url = "https://api.x.ai/v1",
        .reasoning = true,
        .context_window = 131072,
        .max_tokens = 8192,
        .efforts = "low,medium,high",
        .vision = false,
    },
    .{
        .id = "grok-3-mini-fast-latest",
        .name = "Grok 3 Mini Fast Latest",
        .provider = "xai-api",
        .protocol = .openai_responses,
        .base_url = "https://api.x.ai/v1",
        .reasoning = true,
        .context_window = 131072,
        .max_tokens = 8192,
        .efforts = "low,medium,high",
        .vision = false,
    },
    .{
        .id = "grok-3-mini-latest",
        .name = "Grok 3 Mini Latest",
        .provider = "xai-api",
        .protocol = .openai_responses,
        .base_url = "https://api.x.ai/v1",
        .reasoning = true,
        .context_window = 131072,
        .max_tokens = 8192,
        .efforts = "low,medium,high",
        .vision = false,
    },
    .{
        .id = "grok-4",
        .name = "Grok 4",
        .provider = "xai-api",
        .protocol = .openai_responses,
        .base_url = "https://api.x.ai/v1",
        .reasoning = true,
        .context_window = 256000,
        .max_tokens = 64000,
        .efforts = "",
        .vision = false,
    },
    .{
        .id = "grok-4-1-fast",
        .name = "Grok 4.1 Fast",
        .provider = "xai-api",
        .protocol = .openai_responses,
        .base_url = "https://api.x.ai/v1",
        .reasoning = true,
        .context_window = 2000000,
        .max_tokens = 30000,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "grok-4-1-fast-non-reasoning",
        .name = "Grok 4.1 Fast (Non-Reasoning)",
        .provider = "xai-api",
        .protocol = .openai_responses,
        .base_url = "https://api.x.ai/v1",
        .reasoning = false,
        .context_window = 2000000,
        .max_tokens = 30000,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "grok-4-fast",
        .name = "Grok 4 Fast",
        .provider = "xai-api",
        .protocol = .openai_responses,
        .base_url = "https://api.x.ai/v1",
        .reasoning = true,
        .context_window = 2000000,
        .max_tokens = 30000,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "grok-4-fast-non-reasoning",
        .name = "Grok 4 Fast (Non-Reasoning)",
        .provider = "xai-api",
        .protocol = .openai_responses,
        .base_url = "https://api.x.ai/v1",
        .reasoning = false,
        .context_window = 2000000,
        .max_tokens = 30000,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "grok-4.20-0309-non-reasoning",
        .name = "Grok 4.20 (Non-Reasoning)",
        .provider = "xai-api",
        .protocol = .openai_responses,
        .base_url = "https://api.x.ai/v1",
        .reasoning = false,
        .context_window = 1000000,
        .max_tokens = 30000,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "grok-4.20-0309-reasoning",
        .name = "Grok 4.20 (Reasoning)",
        .provider = "xai-api",
        .protocol = .openai_responses,
        .base_url = "https://api.x.ai/v1",
        .reasoning = true,
        .context_window = 1000000,
        .max_tokens = 30000,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "grok-4.20-beta-latest-non-reasoning",
        .name = "Grok 4.20 Beta (Non-Reasoning)",
        .provider = "xai-api",
        .protocol = .openai_responses,
        .base_url = "https://api.x.ai/v1",
        .reasoning = false,
        .context_window = 2000000,
        .max_tokens = 30000,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "grok-4.20-beta-latest-reasoning",
        .name = "Grok 4.20 Beta (Reasoning)",
        .provider = "xai-api",
        .protocol = .openai_responses,
        .base_url = "https://api.x.ai/v1",
        .reasoning = true,
        .context_window = 2000000,
        .max_tokens = 30000,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "grok-4.20-multi-agent-beta-latest",
        .name = "Grok 4.20 Multi-Agent Beta",
        .provider = "xai-api",
        .protocol = .openai_responses,
        .base_url = "https://api.x.ai/v1",
        .reasoning = true,
        .context_window = 2000000,
        .max_tokens = 30000,
        .efforts = "low,medium,high,xhigh",
        .vision = true,
    },
    .{
        .id = "grok-4.3",
        .name = "Grok 4.3",
        .provider = "xai-api",
        .protocol = .openai_responses,
        .base_url = "https://api.x.ai/v1",
        .reasoning = true,
        .context_window = 1000000,
        .max_tokens = 30000,
        .efforts = "low,medium,high",
        .vision = true,
    },
    .{
        .id = "grok-4.5",
        .name = "Grok 4.5",
        .provider = "xai-api",
        .protocol = .openai_responses,
        .base_url = "https://api.x.ai/v1",
        .reasoning = true,
        .context_window = 500000,
        .max_tokens = 500000,
        .efforts = "low,medium,high",
        .vision = true,
    },
    .{
        .id = "grok-4.6",
        .name = "Grok 4.6",
        .provider = "xai-api",
        .protocol = .openai_responses,
        .base_url = "https://api.x.ai/v1",
        .reasoning = true,
        .context_window = 500000,
        .max_tokens = 500000,
        .efforts = "low,medium,high,xhigh",
        .vision = true,
    },
    .{
        .id = "grok-beta",
        .name = "Grok Beta",
        .provider = "xai-api",
        .protocol = .openai_responses,
        .base_url = "https://api.x.ai/v1",
        .reasoning = false,
        .context_window = 131072,
        .max_tokens = 4096,
        .efforts = "",
        .vision = false,
    },
    .{
        .id = "grok-build-0.1",
        .name = "Grok Build 0.1",
        .provider = "xai-api",
        .protocol = .openai_responses,
        .base_url = "https://api.x.ai/v1",
        .reasoning = true,
        .context_window = 256000,
        .max_tokens = 256000,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "grok-code-fast-1",
        .name = "Grok Code Fast 1",
        .provider = "xai-api",
        .protocol = .openai_responses,
        .base_url = "https://api.x.ai/v1",
        .reasoning = true,
        .context_window = 256000,
        .max_tokens = 10000,
        .efforts = "",
        .vision = false,
    },
    .{
        .id = "grok-vision-beta",
        .name = "Grok Vision Beta",
        .provider = "xai-api",
        .protocol = .openai_responses,
        .base_url = "https://api.x.ai/v1",
        .reasoning = false,
        .context_window = 8192,
        .max_tokens = 4096,
        .efforts = "",
        .vision = true,
    },
    // -- OpenAI --------------------------------------------------------------
    //
    // /v1/models publishes ids only, so everything here is transcribed. The
    // Codex rows carry the subscription window (400K), not the API one (1M):
    // a ChatGPT login routes through the Codex backend, which caps there.
    .{
        .id = "gpt-5.6-sol",
        .name = "GPT-5.6 Sol",
        .provider = "openai-codex",
        .protocol = .openai_responses,
        .base_url = "https://chatgpt.com/backend-api",
        .reasoning = true,
        .context_window = 400000,
        .max_tokens = 128000,
        .efforts = "none,low,medium,high,xhigh,max",
        .vision = true,
    },
    .{
        .id = "gpt-5.6-terra",
        .name = "GPT-5.6 Terra",
        .provider = "openai-codex",
        .protocol = .openai_responses,
        .base_url = "https://chatgpt.com/backend-api",
        .reasoning = true,
        .context_window = 400000,
        .max_tokens = 128000,
        .efforts = "none,low,medium,high,xhigh,max",
        .vision = true,
    },
    .{
        .id = "gpt-5.6-luna",
        .name = "GPT-5.6 Luna",
        .provider = "openai-codex",
        .protocol = .openai_responses,
        .base_url = "https://chatgpt.com/backend-api",
        .reasoning = true,
        .context_window = 400000,
        .max_tokens = 128000,
        .efforts = "none,low,medium,high,xhigh,max",
        .vision = true,
    },
    .{
        .id = "gpt-5.3-codex",
        .name = "GPT-5.3 Codex",
        .provider = "openai-codex",
        .protocol = .openai_responses,
        .base_url = "https://chatgpt.com/backend-api",
        .reasoning = true,
        .context_window = 400000,
        .max_tokens = 128000,
        .efforts = "low,medium,high,xhigh",
        .vision = true,
    },
    .{
        .id = "gpt-5.6",
        .name = "GPT-5.6",
        .provider = "openai",
        .protocol = .openai_compat,
        .base_url = "https://api.openai.com/v1",
        .reasoning = true,
        .context_window = 1050000,
        .max_tokens = 128000,
        .efforts = "none,low,medium,high,xhigh,max",
        .vision = true,
    },
    .{
        .id = "gpt-5.5",
        .name = "GPT-5.5",
        .provider = "openai",
        .protocol = .openai_compat,
        .base_url = "https://api.openai.com/v1",
        .reasoning = true,
        .context_window = 1050000,
        .max_tokens = 128000,
        .efforts = "none,low,medium,high,xhigh",
        .vision = true,
    },
    .{
        .id = "gpt-5.6-sol",
        .name = "GPT-5.6 Sol",
        .provider = "openai-codex-device",
        .protocol = .openai_responses,
        .base_url = "https://chatgpt.com/backend-api",
        .reasoning = true,
        .context_window = 400000,
        .max_tokens = 128000,
        .efforts = "none,low,medium,high,xhigh,max",
        .vision = true,
    },
    // -- Command Code ---------------------------------------------------------
    //
    // A router in front of every vendor. `registry.load` fetches /models and
    // enriches vision/reasoning/protocol from their docs into
    // `cache/caps-commandcode.json`. These rows are the offline seed only:
    // live + cache win when present. Claude ids use `.anthropic` (must hit
    // /messages); everything else uses chat.completions.
    .{
        .id = "claude-sonnet-5",
        .name = "Claude Sonnet 5",
        .provider = "commandcode",
        .protocol = .anthropic,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 1000000,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "claude-sonnet-4-6",
        .name = "Claude Sonnet 4.6",
        .provider = "commandcode",
        .protocol = .anthropic,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = false,
        .context_window = 1000000,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "claude-fable-5",
        .name = "Claude Fable 5",
        .provider = "commandcode",
        .protocol = .anthropic,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 1000000,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "claude-opus-5",
        .name = "Claude Opus 5",
        .provider = "commandcode",
        .protocol = .anthropic,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 1000000,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "claude-opus-4-8",
        .name = "Claude Opus 4.8",
        .provider = "commandcode",
        .protocol = .anthropic,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 1000000,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "claude-opus-4-7",
        .name = "Claude Opus 4.7",
        .provider = "commandcode",
        .protocol = .anthropic,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 1000000,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "claude-haiku-4-5-20251001",
        .name = "Claude Haiku 4.5",
        .provider = "commandcode",
        .protocol = .anthropic,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = false,
        .context_window = 200000,
        .max_tokens = 0,
        .efforts = "",
        .vision = false,
    },
    .{
        .id = "gpt-5.6-sol",
        .name = "GPT-5.6 Sol",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 1050000,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "gpt-5.6-terra",
        .name = "GPT-5.6 Terra",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 1050000,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "gpt-5.6-luna",
        .name = "GPT-5.6 Luna",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 1050000,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "gpt-5.5",
        .name = "GPT-5.5",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 400000,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "gpt-5.4",
        .name = "GPT-5.4",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 400000,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "gpt-5.3-codex",
        .name = "GPT-5.3 Codex",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 400000,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "gpt-5.4-mini",
        .name = "GPT-5.4 Mini",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 400000,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "deepseek/deepseek-v4-pro",
        .name = "DeepSeek V4 Pro (latest)",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 1000000,
        .max_tokens = 0,
        .efforts = "",
        .vision = false,
    },
    .{
        .id = "deepseek/deepseek-v4-flash",
        .name = "DeepSeek V4 Flash (latest)",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 1000000,
        .max_tokens = 0,
        .efforts = "",
        .vision = false,
    },
    .{
        .id = "deepseek/deepseek-v4-flash-vision-exp",
        .name = "DeepSeek V4 Flash Vision (exp)",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 1000000,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "moonshotai/Kimi-K3",
        .name = "Kimi K3",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 1000000,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "moonshotai/Kimi-K2.7-Code",
        .name = "Kimi K2.7 Code",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 256000,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "moonshotai/Kimi-K2.7-Code-Highspeed",
        .name = "Kimi K2.7 Code HighSpeed",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 262000,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "moonshotai/Kimi-K2.6",
        .name = "Kimi K2.6",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = false,
        .context_window = 256000,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "moonshotai/Kimi-K2.5",
        .name = "Kimi K2.5",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = false,
        .context_window = 256000,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "zai-org/GLM-5.3",
        .name = "GLM-5.3",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 1000000,
        .max_tokens = 0,
        .efforts = "",
        .vision = false,
    },
    .{
        .id = "zai-org/GLM-5.2",
        .name = "GLM-5.2",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 1000000,
        .max_tokens = 0,
        .efforts = "",
        .vision = false,
    },
    .{
        .id = "zai-org/GLM-5.2-Fast",
        .name = "GLM-5.2 Fast",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = false,
        .context_window = 1000000,
        .max_tokens = 0,
        .efforts = "",
        .vision = false,
    },
    .{
        .id = "zai-org/GLM-5.1",
        .name = "GLM-5.1",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = false,
        .context_window = 200000,
        .max_tokens = 0,
        .efforts = "",
        .vision = false,
    },
    .{
        .id = "zai-org/GLM-5",
        .name = "GLM-5",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = false,
        .context_window = 200000,
        .max_tokens = 0,
        .efforts = "",
        .vision = false,
    },
    .{
        .id = "MiniMaxAI/MiniMax-M3",
        .name = "MiniMax M3",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 1000000,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "MiniMaxAI/MiniMax-M2.7",
        .name = "MiniMax M2.7",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = false,
        .context_window = 200000,
        .max_tokens = 0,
        .efforts = "",
        .vision = false,
    },
    .{
        .id = "MiniMaxAI/MiniMax-M2.5",
        .name = "MiniMax M2.5",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = false,
        .context_window = 200000,
        .max_tokens = 0,
        .efforts = "",
        .vision = false,
    },
    .{
        .id = "xiaomi/mimo-v2.5-pro",
        .name = "MiMo V2.5 Pro",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = false,
        .context_window = 1000000,
        .max_tokens = 0,
        .efforts = "",
        .vision = false,
    },
    .{
        .id = "xiaomi/mimo-v2.5",
        .name = "MiMo V2.5",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = false,
        .context_window = 1000000,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "Qwen/Qwen3.8-Max",
        .name = "Qwen 3.8 Max",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 1000000,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "Qwen/Qwen3.8-27B",
        .name = "Qwen 3.8 27B",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 262144,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "Qwen/Qwen3.7-Max",
        .name = "Qwen 3.7 Max",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 1000000,
        .max_tokens = 0,
        .efforts = "",
        .vision = false,
    },
    .{
        .id = "Qwen/Qwen3.7-Plus",
        .name = "Qwen 3.7 Plus",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 1000000,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "Qwen/Qwen3.7-Flash",
        .name = "Qwen 3.7 Flash",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 1000000,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "Qwen/Qwen3.6-Max-Preview",
        .name = "Qwen 3.6 Max Preview",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 200000,
        .max_tokens = 0,
        .efforts = "",
        .vision = false,
    },
    .{
        .id = "Qwen/Qwen3.6-Plus",
        .name = "Qwen 3.6 Plus",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 200000,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "stepfun/Step-3.7-Flash",
        .name = "Step 3.7 Flash",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 256000,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "stepfun/Step-3.5-Flash",
        .name = "Step 3.5 Flash",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 1000000,
        .max_tokens = 0,
        .efforts = "",
        .vision = false,
    },
    .{
        .id = "tencent/hy3-paid",
        .name = "Tencent Hy3",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 262144,
        .max_tokens = 0,
        .efforts = "",
        .vision = false,
    },
    .{
        .id = "google/gemini-3.7-flash",
        .name = "Gemini 3.7 Flash",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 1048576,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "google/gemini-3.6-flash",
        .name = "Gemini 3.6 Flash",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 1000000,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "google/gemini-3.5-flash",
        .name = "Gemini 3.5 Flash",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 1000000,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "google/gemini-3.5-flash-lite",
        .name = "Gemini 3.5 Flash Lite",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 1000000,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "google/gemini-3.1-flash-lite",
        .name = "Gemini 3.1 Flash Lite",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 1000000,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "sakana/fugu-ultra",
        .name = "Fugu Ultra",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 1000000,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "nvidia/nemotron-3-ultra-550b-a55b",
        .name = "Nemotron 3 Ultra",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 1000000,
        .max_tokens = 0,
        .efforts = "",
        .vision = false,
    },
    .{
        .id = "thinkingmachines/inkling",
        .name = "Inkling",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 256000,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "thinkingmachines/inkling-small",
        .name = "Inkling Small",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 1000000,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "stealth/ox-alpha",
        .name = "Ox Alpha",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 1048576,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "poolside/laguna-s-2.1-free",
        .name = "Laguna S 2.1",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 256000,
        .max_tokens = 0,
        .efforts = "",
        .vision = false,
    },
    .{
        .id = "meta/muse-spark-1.1",
        .name = "Muse Spark 1.1",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 1048576,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "meta/muse-spark-1.2",
        .name = "Muse Spark 1.2",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 1048576,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "meta/muse-spark-1.2-contributor",
        .name = "Muse Spark 1.2 Contributor",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 1048576,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "xai/grok-4.5",
        .name = "Grok 4.5",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 500000,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "xai/grok-4.6",
        .name = "Grok 4.6",
        .provider = "commandcode",
        .protocol = .openai_compat,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 500000,
        .max_tokens = 0,
        .efforts = "",
        .vision = false,
    },
    .{
        .id = "claude-sonnet-5",
        .name = "Claude Sonnet 5",
        .provider = "commandcode-anthropic",
        .protocol = .anthropic,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 1000000,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "claude-sonnet-4-6",
        .name = "Claude Sonnet 4.6",
        .provider = "commandcode-anthropic",
        .protocol = .anthropic,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = false,
        .context_window = 1000000,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "claude-fable-5",
        .name = "Claude Fable 5",
        .provider = "commandcode-anthropic",
        .protocol = .anthropic,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 1000000,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "claude-opus-5",
        .name = "Claude Opus 5",
        .provider = "commandcode-anthropic",
        .protocol = .anthropic,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 1000000,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "claude-opus-4-8",
        .name = "Claude Opus 4.8",
        .provider = "commandcode-anthropic",
        .protocol = .anthropic,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 1000000,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "claude-opus-4-7",
        .name = "Claude Opus 4.7",
        .provider = "commandcode-anthropic",
        .protocol = .anthropic,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = true,
        .context_window = 1000000,
        .max_tokens = 0,
        .efforts = "",
        .vision = true,
    },
    .{
        .id = "claude-haiku-4-5-20251001",
        .name = "Claude Haiku 4.5",
        .provider = "commandcode-anthropic",
        .protocol = .anthropic,
        .base_url = "https://api.commandcode.ai/provider/v1",
        .reasoning = false,
        .context_window = 200000,
        .max_tokens = 0,
        .efforts = "",
        .vision = false,
    },
    // -- Anthropic -----------------------------------------------------------
    //
    // The models endpoint publishes effort levels and max_input_tokens, so
    // these are the offline fallback only. The Pro/Max row stays at 200K: the
    // 1M window needs the context-1m beta header, which a subscription token
    // cannot send.
    .{
        .id = "claude-opus-4-8",
        .name = "Claude Opus 4.8",
        .provider = "anthropic",
        .protocol = .anthropic,
        .base_url = "https://api.anthropic.com",
        .reasoning = true,
        .context_window = 200000,
        .max_tokens = 64000,
        .efforts = "low,medium,high,xhigh,max",
        .vision = true,
    },
    .{
        .id = "claude-opus-4-8",
        .name = "Claude Opus 4.8",
        .provider = "anthropic-api",
        .protocol = .anthropic,
        .base_url = "https://api.anthropic.com",
        .reasoning = true,
        .context_window = 1000000,
        .max_tokens = 64000,
        .efforts = "low,medium,high,xhigh,max",
        .vision = true,
    },
};

pub fn lookup(provider: []const u8, id: []const u8) ?Model {
    for (all) |m| {
        if (std.mem.eql(u8, m.provider, provider) and std.mem.eql(u8, m.id, id)) return m;
    }
    for (all) |m| {
        if (std.mem.eql(u8, m.id, id)) return m;
    }
    return null;
}

pub fn forProvider(provider: []const u8, out: []Model) usize {
    var n: usize = 0;
    for (all) |m| {
        if (!std.mem.eql(u8, m.provider, provider)) continue;
        if (n >= out.len) break;
        out[n] = m;
        n += 1;
    }
    return n;
}

test "no model offers a level its vendor does not have" {
    for (all) |m| {
        var it = std.mem.splitScalar(u8, m.efforts, ',');
        while (it.next()) |level| {
            if (level.len == 0) continue;
            const known = std.mem.eql(u8, level, "none") or
                std.mem.eql(u8, level, "low") or
                std.mem.eql(u8, level, "medium") or
                std.mem.eql(u8, level, "high") or
                std.mem.eql(u8, level, "xhigh") or
                std.mem.eql(u8, level, "max");
            try std.testing.expect(known);
            // Nothing current takes `minimal`: xAI never had it, and OpenAI
            // spells its floor `none`. A request carrying it is rejected.
            try std.testing.expect(!std.mem.eql(u8, level, "minimal"));
            // `ultra` is a Codex mode, not an effort value.
            try std.testing.expect(!std.mem.eql(u8, level, "ultra"));
        }
        // A model with levels reasons, and one that reasons is not zero-window.
        if (m.efforts.len != 0) try std.testing.expect(m.reasoning);
        try std.testing.expect(m.context_window > 0);
    }
}

test "a subscription row carries the subscription window, not the API one" {
    const sub = lookup("openai-codex", "gpt-5.6-sol").?;
    try std.testing.expectEqual(@as(u32, 400_000), sub.context_window);
    const api = lookup("openai", "gpt-5.6").?;
    try std.testing.expect(api.context_window > sub.context_window);

    const pro = lookup("anthropic", "claude-opus-4-8").?;
    const key = lookup("anthropic-api", "claude-opus-4-8").?;
    // 1M needs the context-1m beta header, which a Pro/Max token cannot send.
    try std.testing.expectEqual(@as(u32, 200_000), pro.context_window);
    try std.testing.expectEqual(@as(u32, 1_000_000), key.context_window);
}

test "a provider string that is not a catalog id makes its rows unreachable" {
    for (all) |m| {
        if (@import("catalog.zig").byId(m.provider) == null) {
            std.debug.print("{s} is not a provider id\n", .{m.provider});
            return error.UnknownProvider;
        }
    }
}

test "every catalog default model is in the table" {
    for (@import("catalog.zig").all) |spec| {
        if (lookup(spec.id, spec.model) == null) {
            std.debug.print("no row for {s}/{s}\n", .{ spec.id, spec.model });
            return error.MissingModelRow;
        }
    }
}

test "grok-4.6 oauth has window and efforts" {
    const m = lookup("xai-oauth", "grok-4.6").?;
    try std.testing.expectEqual(@as(u32, 500_000), m.context_window);
    try std.testing.expectEqual(@as(u32, 500_000), m.max_tokens);
    try std.testing.expect(m.reasoning);
    try std.testing.expect(std.mem.indexOf(u8, m.efforts, "high") != null);
    try std.testing.expectEqual(types.Protocol.openai_responses, m.protocol);
}

test "xai-oauth lists nine models" {
    var buf: [16]Model = undefined;
    const n = forProvider("xai-oauth", &buf);
    try std.testing.expectEqual(@as(usize, 9), n);
}

test "command code vision is carried here, because the catalog does not publish it" {
    // Their /models route returns id, name and context_length only. If this
    // table says text-only, the picker says text-only, and a model that reads
    // images looks like one that cannot.
    var vision: usize = 0;
    var total: usize = 0;
    for (all) |m| {
        if (!std.mem.eql(u8, m.provider, "commandcode")) continue;
        total += 1;
        if (m.vision) vision += 1;
    }
    try std.testing.expectEqual(@as(usize, 58), total);
    try std.testing.expectEqual(@as(usize, 40), vision);

    try std.testing.expect(lookup("commandcode", "claude-opus-5").?.vision);
    try std.testing.expect(lookup("commandcode", "google/gemini-3.7-flash").?.vision);
    try std.testing.expect(lookup("commandcode", "Qwen/Qwen3.8-27B").?.vision);
    // Named for vision and still text-only upstream: taken from their table,
    // not from the id.
    try std.testing.expect(!lookup("commandcode", "deepseek/deepseek-v4-flash").?.vision);
}
